CHANGES.md
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/EffectedVideoChatActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/EffectedVideoChatSetupActivity.kt
webrtc-video-effector/src/main/cpp/yuvconv.c
webrtc-video-effector/src/main/java/jp/shiguredo/webrtc/video/effector/CapturerObserverProxy.java
webrtc-video-effector/src/main/java/jp/shiguredo/webrtc/video/effector/RTCVideoEffector.java
webrtc-video-effector/src/main/java/jp/shiguredo/webrtc/video/effector/VideoEffectorContext.java
webrtc-video-effector/src/main/java/jp/shiguredo/webrtc/video/effector/format/LibYuvBridge.java
webrtc-video-effector/src/main/java/jp/shiguredo/webrtc/video/effector/format/YuvByteBufferDumper.java
webrtc-video-effector/src/main/java/jp/shiguredo/webrtc/video/effector/format/YuvByteBufferReader.java

#3 で報告された、Effected video chat で I420 から変換された RGB データがずれていた問題を修正した。
- これに伴い、NV12/NV21 の経由を廃止し、I420 と RGBA の直接の相互変換とした
また、#3 の workaround で入れてもらっていたエフェクトふたつを追加した。
- セピア化のエフェクト
- デバッグ、比較用としてなにもしないエフェクト
Thanks to @daneko

YUV から RGB への変換がずれていた問題を修正する

---

samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/SpotlightRoomSetupActivity.kt

スポットライト (≠スポットライト・レガシー) ではサイマルキャストが利用されていますが、サイマルキャストでは VP9 が利用できません。
スポットライト画面の映像コーデックから VP9 を削除し、選択できなくします。

スポットライトで VP9 を選択できなくする

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
samples/build.gradle
webrtc-video-effector/build.gradle

- 依存ライブラリーをアップデートしました
- kotlin の `-M1` はマイルストーン・プレビューなので更新対象から外しています
- kotlin-android-extensions の警告が出ていますが、影響範囲が大きいのでこの PR では対応しません
作業後の `./gradlew dependencyUpdates` の実行結果は以下のとおりです
```
$ ./gradlew dependencyUpdates
Starting a Gradle Daemon, 2 incompatible and 2 stopped Daemons could not be reused, use --status for details
> Configure project :samples
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
> Task :dependencyUpdates
dependencyUpdates.resolutionStrategy: Remove the assignment operator, '=', when setting this task property …
```

依存ライブラリのアップデート

---

CHANGES.md
samples/src/main/kotlin/jp/shiguredo/sora/sample/facade/SoraVideoChannel.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/SimulcastActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/SimulcastSetupActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/SpotlightRoomSetupActivity.kt
samples/src/main/res/layout/activity_simulcast_setup.xml
samples/src/main/res/layout/activity_spotlight_room_setup.xml

- サイマルキャスト画面から simulcast_rid を指定可能にしました
- スポットライト画面から spotlight_focus_rid / spotlight_unfocus_rid を指定しました
- 追加した設定項目のラベル名
- 動作確認に利用した Pixel 4 では `非フォーカス時の RID` というラベルがはみ出してしまっている
- RID を小文字にして改善 https://github.com/shiguredo/sora-android-sdk-samples/pull/32#issuecomment-876093610 
動作確認には sora-android-sdk の以下のブランチを参照する必要があります
https://github.com/shiguredo/sora-android-sdk/pull/46
- サイマルキャストで simulcast_rid が指定できる
- signaling.log から確認
- スポットライトで spotlight_focus_rid / spotlight_unfocus_rid を指定できる
- signaling.log から確認
- スポットライト・レガシーで Sora に接続できる
- その際、シグナリング・メッセージに spotlight_focus_rid / spotlight_unfocus_rid が含まれていない

サイマルキャスト画面とスポットライト画面の改善

---

CHANGES.md
samples/build.gradle

- gradle.properties で指定した usesCleartextTraffic が参照されない問題を修正しました
- sora-android-sdk-quickstart https://github.com/shiguredo/sora-android-sdk-quickstart/search?q=usesCleartextTraffic
- sora-android-sdk-samples https://github.com/shiguredo/sora-android-sdk-samples/search?q=usesCleartextTraffic

gradle.properties で指定した usesCleartextTraffic が参照されない問題を修正する

---

build.gradle
samples/build.gradle

- permissions-dispatcher を Maven Central から取得するように修正しました
- 修正前は permissions-dispatcher を JitPack から取得していました

permissions-dispatcher を Maven Central から取得する

---

CHANGES.md
build.gradle
gradle.properties.example

クイックスタートで対応してレビューしていただいた内容と同様の修正となっています。
https://github.com/shiguredo/sora-android-sdk-quickstart/pull/10

シグナリング URL の設定を build.gradle から gradle.properties に移動する

---

CHANGES.md
samples/src/main/kotlin/jp/shiguredo/sora/sample/facade/SoraVideoChannel.kt

ビデオチャットサンプルから映像の有無：無効をして接続した時、相手の codec が H.264 だとサンプルの接続がエラーとなる事象について対応しました。
Android SDK 側は `SoraMediaOption.videoDownstreamContext` が未設定の場合は `SoftwareVideoEncoderFactory` を使用するようになっていましたが、H.264 は `SoftwareVideoEncoderFactory` で扱えないためにエラーとなっていました。
https://github.com/shiguredo/sora-android-sdk/blob/develop/sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/channel/rtc/RTCComponentFactory.kt#L45-L55
`SoraMediaOption.videoDownstreamContext` が未設定なのは、ビデオチャットサンプルにて`映像の有無`を`無効`に設定した場合に`SoraMediaOption.videoDownstreamContext` を設定しない動作となっていたため、これを修正しています。
~~音声についても同様に修正をしています。~~
ボイスチャットサンプルについても同様の事象が発生していますがこの PR では未対応です。
双方とも映像を無効にすることを想定したサンプルであるため、対応は行っていません。

sendrecv 接続時に映像の送信を無効に設定し、かつ相手が H.264 の映像を送信するとき接続が失敗する不具合を修正する

---

samples/src/main/kotlin/jp/shiguredo/sora/sample/facade/SoraAudioChannel.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/facade/SoraVideoChannel.kt

- Sora との接続時に connectedSignalingEndpoint を出力するように修正しました
- SDK 側の https://github.com/shiguredo/sora-android-sdk/pull/65 に対応する変更です

Sora との接続時に connectedSignalingEndpoint を出力する

---

CHANGES.md
gradle.properties.example
samples/build.gradle
samples/src/main/kotlin/jp/shiguredo/sora/sample/facade/SoraAudioChannel.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/screencast/SoraScreencastService.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/EffectedVideoChatActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/ScreencastSetupActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/SimulcastActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/VideoChatRoomActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/VoiceChatRoomActivity.kt

概要
---
シグナリングで送信するメタデータについて外部ファイルから設定ができるようにしました。
`signaling_metadata` という項目名で追加をしています。
今まで SoraLabo と Android Samples を接続するにはプログラムの修正が必要でしたが今後は不要となり、
気軽に Android Samples を試してもらえるようになると思います。
修正箇所についての補足
---
- 外部ファイルに設定をするにあたり、二重にエスケープをする必要が出ています。外部ファイルには設定例を記載しています。
`build.gradle` でのクラスファイル生成時、Gsonで文字列を map に変換時の2回エスケープが必要だったためです。
https://github.com/shiguredo/sora-android-sdk-samples/compare/feature/add-signaling-metadata-setting?expand=1#diff-bbb7dbbc87a5eeefd96280835e68694ed252637b5b87bce74364c0e4ea56bca4R28-R29
- 設定内容が空、null であった時の Sora への送信内容は以下の通りでした。
- `signaling_metadata` 自体を設定しない -> ビルドエラー
- `signaling_metadata =` を設定 -> map が null となり、Sora に metadata が送信されない
- `signaling_metadata ={}` を設定 -> Sora に `"metadata": {}` を送信

シグナリング接続時に送信するメタデータを外部ファイルから設定できるようにする

---

samples/src/main/kotlin/jp/shiguredo/sora/sample/option/SoraFrameSize.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/SimulcastActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/SimulcastSetupActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/SpotlightRoomSetupActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/VideoChatRoomActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/VideoChatRoomSetupActivity.kt

- ビデオチャット
- 全ての解像度を指定可能にしました
- Landscape の解像度が上に表示されます
- サイマルキャストスポットライト
- 指定できる解像度を Portrait から Landscape に変更しました

解像度に Landscape と Portrait の両方を追加する & Landscape と Portrait の優先度を変える

---

CHANGES.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
samples/build.gradle
samples/src/main/AndroidManifest.xml

依存パッケージのアップデートを行っています。動作確認済みです。
また、アップデートに必要であったため、 compileSdkVersion 31 に上げる変更を行なっています。
クイックスタートやサンプルは SDK 本体ではないためアップデートしてよいと考えています。
特記事項
- Kotlin の  1.7.0 関連のアップデートは見送っています。影響未確認の部分があって慎重に作業をしたいため別にします。
- Android Studio のバージョンを 2021.2.1 にあげていただく必要があります
- AndroidManifest .xml の修正は compileSdkVersion 31 に上げるに伴い必要になりました
https://developer.android.com/about/versions/12/behavior-changes-12?hl=ja#exported

利用ライブラリをアップデートする

---

CHANGES.md
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/MessagingActivity.kt

接続相手に sendrecv H.264 で接続しているクライアントがいるときにメッセージングアプリが接続エラーになる問題が発生していました。
`mediaOption.enableVideoDownstream()` に eglContext を設定することで事象が改善したので PR にしました。
最小限の修正をして、動いたからよし、としてしまっています。問題ないか確認をしていただけると助かります。。

enableVideoDownstream に eglContext を設定する

---

CHANGES.md

CHANGE.md のフォーマット修正です。インデント 2 と 4 が混在していたので 4 に統一しています。
markdownlint のクイックフィックスを利用しており、リンク URL を `<>` で囲む修正も入っています。囲むことが正しいためクイックフィックスの結果を採用しています。

CHANGES.md のインデントを 4 にそろえる

---

CHANGES.md
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/ScreencastSetupActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/SpotlightRoomSetupActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/VideoChatRoomSetupActivity.kt

サンプルの映像コーデックに AV1 を追加しました。
追加したサンプルはコミットログより確認ください。
スポットライトサンプルもサイマルキャストを無効にすれば AV1 が利用可能であるため追加しています。（サイマルキャスト を選択すると Sora 側でエラーとなりアプリが終了します）
Sora 側のエラーがアプリに表示されない問題についてはまた別途対応したいと思います。

サンプルに AV1 を追加する

---

.idea/gradle.xml
CHANGES.md
build.gradle
samples/build.gradle
samples/src/main/kotlin/jp/shiguredo/sora/sample/screencast/SoraScreencastService.kt
webrtc-video-effector/build.gradle

sora-android-sdk のライブラリのバージョンアップに合わせてサンプルについてもバージョンアップを実施しました。
最新のバージョンが利用できるように targetSdkVersion のバージョンをあげています。
それに伴い、Target SDK 31 から設定が必須となった PendingIntent. getActivities の flag の設定を追加しています。(b16bbd5930af5edc14f51442a019c5446bd2b6d9)
`PendingIntent.FLAG_MUTABLE` を設定していますが、これはデフォルトの動きを踏襲する設定です。

依存ライブラリのバージョンアップとそれに付随する対応

---

samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/SimulcastSetupActivity.kt

サイマルキャストのテスト画面にて、選択可能な映像コーデックに VP9 と AV1 を追加します。
本 PR は Sora Android SDK が VP9 と AV1 のサイマルキャストに対応するためのコードではありません。 VP9 と AV1 のサイマルキャストの対応は Sora Android SDK のアップデートを待つ必要があります。

サイマルキャストの映像コーデックにVP9とAV1を追加する

---

CHANGES.md
samples/src/main/kotlin/jp/shiguredo/sora/sample/facade/SoraVideoChannel.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/VideoChatRoomActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/VideoChatRoomSetupActivity.kt
samples/src/main/res/layout/activity_video_chat_room_setup.xml

ビデオチャットサンプルに映像コーデックのプロファイルを追加しました
- 映像関連の箇所がよいかと思い映像サイズの下に追加しました
- 他の項目とあわせてコンボボックス指定にしました
動作確認をして問題なさそうです。項目名や設定箇所等、もしご意見等ありましたらお願いします。

ビデオチャットにサンプルに映像コーデックのプロファイルを追加する

---

CHANGES.md
samples/src/main/AndroidManifest.xml

Android の Tablet で映像送信中に画面を回転させると Activity の再作成が走ってしまう問題についての対応です。
設定画面を含めて同一の対応をしています。

マルチウィンドウモード時に画面を回転すると Activity が再作成されるのを防ぐ設定を入れる

---

CHANGES.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
samples/build.gradle
samples/src/main/AndroidManifest.xml
webrtc-video-effector/build.gradle
webrtc-video-effector/src/main/AndroidManifest.xml

- [UPDATE] Android Gradle Plugin (AGP) を 8.5.0 にアップグレードする
- Android Studion の AGP Upgrade Assistant を利用してアップグレードされた内容
- `com.android.tools.build:gradle` を 8.5.0 に上げる
- ビルドに利用される Gradle を 8.7 に上げる
- Android マニフェストからビルドファイルにパッケージを移動
- Android マニフェストに定義されていた package を削除
- ビルドファイルに namespace を追加
- ビルドファイルの dependencies の transitive をコメントアウト
- AGP 8.5.0 対応で発生したビルドスクリプトのエラーを手動で修正した内容
- AGP 8.0 から buildConfig がデフォルト false になったため、true に設定する
---
This pull request includes several updates to upgrade the Android Gradle Plugin (AGP) to version 8.5.0 and make necessary adjustments to the build files and configurations. The most important changes include upgrading the Gradle version, modifying build configurations, and updating namespaces in the build scripts.
* …

Android Gradle Plugin を 8.5.0 にアップグレード

---

CHANGES.md
build.gradle
samples/build.gradle

変更内容
- [UPDATE] 依存ライブラリーのバージョンを上げる
- com.google.code.gson:gson を 2.11.0 に上げる
- androidx.appcompat:appcompat を 1.7.0 に上げる
- androidx.recyclerview:recyclerview を 1.3.2 に上げる
- com.google.android.material:material を 1.12.0 に上げる
- androidx.navigation:navigation-fragment-ktx を 2.7.7 に上げる
- androidx.navigation:navigation-ui-ktx を 2.7.7 に上げる
- androidx.compose.ui:ui を 1.6.8 に上げる
- androidx.compose.material:material を 1.6.8 に上げる
- androidx.compose.material:material-icons-extended を 1.6.8 に上げる
- androidx.activity:activity-compose を 1.9.1 に上げる
- [UPDATE] compileSdkVersion を 34 に上げる
- Android API レベル 34 以降でコンパイルする必要がある依存ライブラリがあるため
- [UPDATE] Kotlin のバージョンを 1.9.25 に上げる
- 合わせて、kotlinCompilerExtensionVersion を 1.5.15 に上げる
---
This pull request includes several updates to dependencies, the compile SDK …

依存ライブラリをバージョンアップする

---

CHANGES.md
samples/src/main/AndroidManifest.xml
samples/src/main/kotlin/jp/shiguredo/sora/sample/screencast/SoraScreencastService.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/screencast/SoraScreencastServiceStarter.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/MainActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/ScreencastSetupActivity.kt

Google Pixel でスクリーンキャストを行う際に**1つのアプリ**にこのサンプル自体を選択した場合にログに `Could not create virtual display` と表示され配信が行われなくなってしまう問題を改善します。
根本的な原因としてはログの通り `createVirtualDisplay` に失敗しているため発生しています。これを回避するためには `SoraScreencastService` を起動する Activity のタスクを分けることで回避できることがわかりました。
タスクを分けてしまうため Service を起動する Activity 自体を配信することができないという問題はそのままですが、 Service を起動する Activity をダイアログ的な扱いをする画面遷移設計することでユーザーが違和感なく使えるようにしてあります。
プランA では下記のブランチで1つのアプリ選択において、下部のアイコン一覧のみにサンプルアプリが表示されます。
https://github.com/shiguredo/sora-android-sdk-samples/tree/feature/fix-screencast
このPRのプランBブランチでは下部のアイコン一覧だけでなく、自身のアプリが上部の画面選択に表示されます。
どちらの解決策を取るかは実装するアプリの用途次第かと思うので、2種類実装してみました。
なお、 AndroidManifest で Activity の属性を変える必要があるため、もし両方の実装をアプリに入れる場合は Activity を分割する必要があります。
ちなみに1つのアプリにすると制御用のオーバーレイが配信映像に入らないのは素敵だなと思いました。

Pixel で1つのアプリをキャストした際の不自然な挙動を改善する

---

CHANGES.md
build.gradle
samples/src/main/kotlin/jp/shiguredo/sora/sample/facade/SoraAudioChannel.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/facade/SoraVideoChannel.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/screencast/SoraScreencastService.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/MessagingActivity.kt
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/VoiceChatRoomActivity.kt

- [UPDATE] Sora Android SDK を 2025.2.0 にあげる
- onError(SoraMediaChannel, SoraErrorReason) の廃止に対応する
- onClose(mediaChannel: SoraMediaChannel) から onClose(mediaChannel: SoraMediaChannel, closeEvent: SoraCloseEvent) へ移行する
- onClose の切断理由についてはログ出力のみで特に個別の画面で取り扱っていないため、SoraAudioChannel, SoraVideoChannel から先の各画面には渡していません
---
This pull request introduces updates to the Sora SDK sample applications to accommodate changes in the SDK's error and close handling mechanisms. The most significant changes include replacing the `onClose` and `onError` methods with updated versions that provide additional context and logging capabilities.
* **Migration of `onClose` method**: The `onClose` method now accepts an additional parameter, `SoraCloseEvent`, providing more detailed information about the close event. …

2025.2.0 canary.12 に上げる

---

CHANGES.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
samples/build.gradle
samples/src/main/AndroidManifest.xml
samples/src/main/kotlin/jp/shiguredo/sora/sample/ui/MessagingActivity.kt
samples/src/main/res/layout/activity_main.xml
samples/src/main/res/layout/activity_screencast_setup.xml
samples/src/main/res/layout/activity_simulcast.xml
samples/src/main/res/layout/activity_simulcast_setup.xml
samples/src/main/res/layout/activity_spotlight_room_setup.xml
samples/src/main/res/layout/activity_video_chat_room.xml
samples/src/main/res/layout/activity_video_chat_room_setup.xml
samples/src/main/res/layout/activity_voice_chat_room.xml
samples/src/main/res/layout/activity_voice_chat_room_setup.xml

- [UPDATE] 依存ライブラリーのバージョンを上げる
- com.google.code.gson:gson を 2.13.1 に上げる
- androidx.appcompat:appcompat を 1.7.1 に上げる
- androidx.recyclerview:recyclerview を 1.4.0 に上げる
- androidx.constraintlayout:constraintlayout を 2.2.1 に上げる
- androidx.navigation:navigation-fragment-ktx を 2.9.3 に上げる
- androidx.navigation:navigation-ui-ktx を 2.9.3 に上げる
- androidx.compose.ui:ui を 1.8.3 に上げる
- androidx.compose.material:material を 1.8.3 に上げる
- androidx.compose.material:material-icons-extended を 1.7.8 に上げる
- androidx.activity:activity-compose を 1.10.1 に上げる
- com.android.tools.build:gradle を 8.11.1 に上げる
- Gradle を 8.14.3 に上げる
- compileSdkVersion を 36 に上げる
- targetSdkVersion を 36 に上げる
- [UPDATE] edge-to-edge の画面表示に対応する
- targetSdkVersion 35 以降 edge-to-edge の画面表示がデフォルトとなった
- 各画面レイアウト に …

依存ライブラリ、targetSdkVersion、Android Gradle Plugin のアップデート
